dist: xenial
language: node_js
node_js:
  - "11.15.0"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: "Lint"
      script:
        - yarn lint 
    - stage: "Test" 
      script: 
        - yarn test
      

notifications:
  email: false
