language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: "Lint"
      script:
        - yarn lint 

notifications:
  email: false
