backend:
  name: github
  repo: tonik-krijor/demo

media_folder: static/assets
public_folder: assets

collections:
  - name: pages
    label: Pages
    files:
      - file: content/pages/index.md
        label: Front page
        name: index
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Body, name: body, , widget: markdown }
